version: '3.8'

services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - php
      - nginx
      - postgres

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Путь к конфигурационному файлу NGINX
      - ./nginx/html:/var/www/html  # Путь к корневой директории проекта
      - ./src:/var/www/src  # Путь к директории src
      - ./authorize.php:/var/www/html/authorize.php  # Монтирование файла authorize.php
      - ./register.php:/var/www/html/register.php  # Монтирование файла register.php
      - ./feed.php:/var/www/html/feed.php  # Монтирование файла feed.php
    depends_on:
      - php

  php:
    image: php:8.3-fpm
    volumes:
      - ./src:/var/www/html  # Путь к директории src
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
